<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>
			Laboratory work 7
		</title>
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <link rel="stylesheet" href="styles.css"/>
    </head>
	<body>
        <h1>Visitors today: <?php echo $contentList["visitorsToday"]; ?></h1>
        <h1>Visitors last week: <?php echo $contentList["visitorsWeek"]; ?></h1>
        <h1>Visitors last month: <?php echo $contentList["visitorsMonth"]; ?></h1>
        <h1>Visitors last year: <?php echo $contentList["visitorsYear"]; ?></h1>
	</body>
</html>
