<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>
			Laboratory work 5
		</title>
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <link rel="stylesheet" href="styles.css"/>
    </head>
	<body>
        <h1>Event list:</h1><br>
        <?php foreach ($contentList as $event): ?>
    		<div class="event">
    			<a href="<?php echo $event["url"] ?>"><?php echo $event["day"].".".$event["month"].".".$event["year"] ?></a>
    		</div>
    	<?php endforeach; ?>
	</body>
</html>
