<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>
			Laboratory work 6
		</title>
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <link rel="stylesheet" href="styles.css"/>
    </head>
	<body>
        <h1>Order</h1>
        <form class="order-form" action="make-order.php" method="POST">
            <?php foreach ($contentList as $orderField): ?>
    			<div class="order__field">
    				<input class="field-input" type="text" name="<?php echo $orderField["orderFieldName"]; ?>" placeholder="<?php echo $orderField["orderFieldCaption"]; ?>" value="" required>
    			</div>
    		<?php endforeach; ?>
    		<button class="order__button" type="submit" name="order">Order!</button>
        </form>
	</body>
</html>
