<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>
			Laboratory work 7
		</title>
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <link rel="stylesheet" href="styles.css"/>
    </head>
	<body>
        <h1>Order</h1>
        <form class="create-cookie-form" action="create-cookie.php" method="POST">
            <?php foreach ($contentList as $cookieField): ?>
    			<div class="cookie__field">
    				<input class="field-input" type="text" name="<?php echo $cookieField["cookieFieldName"]; ?>" placeholder="<?php echo $cookieField["cookieFieldCaption"]; ?>" value="" required>
    			</div>
    		<?php endforeach; ?>
    		<button class="cookie__button" type="submit" name="createCookie">Create cookie</button>
        </form>
        <div class="loaded-cookies">
            <h2>Loaded cookies:</h2>
            <?php foreach ($_COOKIE as $key => $cookie): ?>
    			<?php echo $key."<br>"; ?>
    		<?php endforeach; ?>
        </div>
        <form class="delete-cookies-form" action="delete-cookies.php" method="POST">
    		<button class="cookie__button" type="submit" name="deleteCookies">Delete cookies</button>
        </form>
	</body>
</html>
